name: Auto Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target_arch: [
            arm64-v8a,
            armeabi-v7a
        ]

      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Cross-Compile Toolchains
        run: |
          chmod +x ./.github/workflows/scripts/setup-toolchains.sh
          bash ./.github/workflows/scripts/setup-toolchains.sh
        shell: bash

      - name: Build libMGEx
        run: |
          mkdir b && cd b
          cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET_ARCH="${{matrix.target_arch}}"
          make -j$(nproc)

      - name: Upload libMGEx.so
        uses: actions/upload-artifact@v3
        with:
          name: libMGEx-lib
          path: libMGEx.so



